version: "1.0"
metadata:
  name: "E2E Test Pipeline"
  description: "A pipeline to acquire data from an EEG board, convert it to voltage, and save it to a CSV file."
  version: "1.1.0"
stages:
  - name: "eeg_source"
    type: "eeg_source"
    params:
      driver:
        type: "ElataV2" # Can be "ElataV1", "ElataV2", or "Mock"
        sample_rate: 250
        drdy_pin: 25
        vref: 4.5
        gain: 24.0
        chips:
          - channels: [2]
          - channels: [1]
      batch_size: 32
    outputs: ["raw_data"]

  - name: "to_voltage"
    type: "to_voltage"
    inputs:
      - "eeg_source.raw_data"
    outputs: ["voltage_data"]

  - name: "csv_sink"
    type: "csv_sink"
    params:
      path: "e2e_test_output.csv"
      max_recording_length_minutes: 60
    inputs:
      - "to_voltage.voltage_data"

  - name: "websocket_sink"
    type: "websocket_sink"
    params:
      topic: "eeg_voltage"
    inputs:
      - "to_voltage.voltage_data"
